services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run build | npm run dev"